# Generated by Django 3.2.9 on 2022-01-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=60)),
                ('answer_1', models.CharField(max_length=60)),
                ('answer_2', models.CharField(max_length=60)),
                ('answer_3', models.CharField(max_length=60)),
                ('level', models.IntegerField(default=0)),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
